#ifndef TOKEN_TYPES_HEADER_GUARD
#define TOKEN_TYPES_HEADER_GUARD

enum token_types {
    TOKEN_SCOPE,
    TOKEN_TYPE,
    TOKEN_REFERENCE,
    TOKEN_CALL,
    TOKEN_INSTANCE_CREATOR,
    TOKEN_TYPE_CLASS,
    TOKEN_START_BLOCK,
    TOKEN_END_BLOCK,
    TOKEN_SYMBOL
};

#endif